// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYY4c2zn37R2AbbKAOFZQiMs4GOkbv6ds',
    appId: '1:1034348469825:web:25554abb873b17df81f0c0',
    messagingSenderId: '1034348469825',
    projectId: 'streamapp-4232f',
    authDomain: 'streamapp-4232f.firebaseapp.com',
    storageBucket: 'streamapp-4232f.appspot.com',
    measurementId: 'G-NFGPS3G073',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nDPoH6dNM0-nj8eTpDBRXQvwW6y29DA',
    appId: '1:535881104020:android:963205de2598d2109d9281',
    messagingSenderId: '535881104020',
    projectId: 'streamingapp-51faa',
    storageBucket: 'streamingapp-51faa.appspot.com',
  );

}